## 과제
- per 불러오기
- 모든 주식 per 테이블 만들기
- per 분포표만들기

## I. 페키지 셋팅

In [1]:
!pip install yahoo_fin
!pip install requests_html

Collecting yahoo_fin
  Downloading yahoo_fin-0.8.9.1-py3-none-any.whl (10 kB)
Collecting requests-html
  Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)
Collecting feedparser
  Downloading feedparser-6.0.8-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 3.6 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (2.23.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (1.3.5)
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2018.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->yahoo_fin) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2021.10.8)
Collecting parse
  Downloading parse-1.19.0.tar.gz (30 kB)
Collecting w3lib
  Downloading w3lib-1.22.0-py2.py3-none-any.whl (20 kB)
Collecting pyppeteer>=0.0.14
  Downloading pyppeteer-1.0.2-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.6 MB/s
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests-html->yahoo_fin) (0.0.1)
Collecting fake-useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Collecting pyquery
  Downloading pyquery-1.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.11.3)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Collecting pyee<9.0.0,>=8.1.0
  Downloading pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Collecting websockets<11.0,>=10.0
  Downloading websockets-10.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (111 kB)
     |████████████████████████████████| 111 kB 58.2 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 60.0 MB/s
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.63.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.7.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests-html->yahoo_fin) (4.6.3)
Collecting cssselect>0.7.9
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests-html->yahoo_fin) (4.2.6)
Building wheels for collected packages: fake-useragent, parse, sgmllib3k
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-py3-none-any.whl size=13502 sha256=9965d6af931d2815bdc92adeff83bfaaf0d5f0aac1c079936c2506de521c0dff
  Stored in directory: /root/.cache/pip/wheels/ed/f7/62/50ab6c9a0b5567267ab76a9daa9d06315704209b2c5d032031
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-py3-none-any.whl size=24591 sha256=336f4462dff99bdb97ec9a9f93effac69821e1f52088b2817457ba483f171b6f
  Stored in directory: /root/.cache/pip/wheels/9c/aa/cc/f2228050ccb40f22144b073f15a2c84f11204f29fc0dce028e
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6066 sha256=26db3ffaebe8dc6620dcef7a9804efd4593bdbc1dca9a233b7a5b12e6edcedf7
  Stored in directory: /root/.cache/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built fake-useragent parse sgmllib3k
Installing collected packages: websockets, urllib3, pyee, cssselect, w3lib, sgmllib3k, pyquery, pyppeteer, parse, fake-useragent, requests-html, feedparser, yahoo-fin
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed cssselect-1.1.0 fake-useragent-0.1.11 feedparser-6.0.8 parse-1.19.0 pyee-8.2.2 pyppeteer-1.0.2 pyquery-1.4.3 requests-html-0.10.0 sgmllib3k-1.0.0 urllib3-1.25.11 w3lib-1.22.0 websockets-10.2 yahoo-fin-0.8.9.1
Requirement already satisfied: requests_html in /usr/local/lib/python3.7/dist-packages (0.10.0)
Requirement already satisfied: parse in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.19.0)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests_html) (0.0.1)
Requirement already satisfied: fake-useragent in /usr/local/lib/python3.7/dist-packages (from requests_html) (0.1.11)
Requirement already satisfied: pyquery in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.4.3)
Requirement already satisfied: pyppeteer>=0.0.14 in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from requests_html) (2.23.0)
Requirement already satisfied: w3lib in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.22.0)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (8.2.2)
Requirement already satisfied: urllib3<2.0.0,>=1.25.8 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (1.25.11)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (4.11.3)
Requirement already satisfied: websockets<11.0,>=10.0 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (10.2)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (1.4.4)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (4.63.0)
Requirement already satisfied: certifi>=2021 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (2021.10.8)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests_html) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests_html) (3.7.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests_html) (4.6.3)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests_html) (4.2.6)
Requirement already satisfied: cssselect>0.7.9 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests_html) (1.1.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->requests_html) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->requests_html) (3.0.4)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from w3lib->requests_html) (1.15.0)

In [2]:
import yahoo_fin.stock_info as si
import pandas as pd

## II.기타 필요자료

### 매일 현재 상승 상위 100종목
### 하락 상위 100종목
### 거래량 100종목

In [3]:
si.get_day_gainers()

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM)
0,NEGG,"Newegg Commerce, Inc.",7.74,0.93,13.68,6022000.0,1359000.0,2.854000e+09,38.32
1,ENV,"Envestnet, Inc.",81.13,8.65,11.93,1230000.0,429621.0,4.448000e+09,338.04
2,GOGO,Gogo Inc.,20.62,1.43,7.48,8226000.0,836165.0,2.287000e+09,16.55
3,ACAD,ACADIA Pharmaceuticals Inc.,27.27,1.52,5.90,978352.0,1450000.0,4.396000e+09,NaN
4,CYTK,"Cytokinetics, Incorporated",42.41,2.06,5.11,601859.0,1080000.0,3.599000e+09,NaN
5,MTNOY,MTN Group Limited,12.36,0.57,4.83,20863.0,47062.0,2.241600e+10,24.28
6,TLRY,"Tilray Brands, Inc.",7.33,0.30,4.28,110349000.0,33083000.0,3.524000e+09,NaN
7,AR,Antero Resources Corporation,31.83,1.41,4.64,6461000.0,8829000.0,1.001700e+10,NaN
8,SMPL,The Simply Good Foods Company,40.21,1.81,4.71,792311.0,560744.0,4.060000e+09,202.06
9,RPM,RPM International Inc.,86.92,3.80,4.57,862499.0,646022.0,1.127100e+10,24.84
10,PCRX,"Pacira BioSciences, Inc.",79.90,3.29,4.29,347363.0,513996.0,3.583000e+09,86.85
11,PBF,PBF Energy Inc.,26.44,0.98,3.85,2051000.0,3613000.0,3.182000e+09,13.93
12,BPMC,Blueprint Medicines Corporation,69.13,2.62,3.94,380627.0,697147.0,4.093000e+09,NaN
13,PPC,Pilgrim's Pride Corporation,26.32,0.96,3.79,1109000.0,1124000.0,6.419000e+09,207.24
14,CENX,Century Aluminum Company,27.47,0.95,3.58,765488.0,1909000.0,2.506000e+09,NaN
15,INVVY,Indivior PLC,20.64,0.74,3.72,25660.0,2431.0,2.914000e+09,15.29
16,SRUUF,Sprott Physical Uranium Trust Fund,15.53,0.53,3.53,679984.0,590629.0,2.539000e+09,NaN
17,EBS,Emergent BioSolutions Inc.,43.57,1.49,3.54,173736.0,589972.0,2.200000e+09,10.20
18,TEO,Telecom Argentina S.A.,6.40,0.21,3.39,125877.0,127267.0,2.757000e+09,35.56
19,ALKS,Alkermes plc,29.50,0.93,3.26,1421000.0,1348000.0,4.778000e+09,NaN
20,LLY,Eli Lilly and Company,301.93,9.44,3.23,2434000.0,2950000.0,2.875420e+11,49.33
21,EQT,EQT Corporation,37.37,1.14,3.15,4604000.0,9804000.0,1.405200e+10,NaN
22,OLLI,"Ollie's Bargain Outlet Holdings, Inc.",48.50,1.43,3.04,1020000.0,1388000.0,3.041000e+09,19.96
23,IMBBY,Imperial Brands PLC,22.18,0.68,3.19,103242.0,189355.0,2.108500e+10,5.66
24,EXC,Exelon Corporation,49.31,1.51,3.16,6101000.0,10824000.0,4.833100e+10,28.34
25,IBDRY,"Iberdrola, S.A.",46.90,1.42,3.12,53649.0,156209.0,7.382900e+10,18.38
26,RES,"RPC, Inc.",10.87,0.29,2.74,1162000.0,1543000.0,2.353000e+09,362.33
27,KNSL,"Kinsale Capital Group, Inc.",237.70,6.92,3.00,80124.0,111050.0,5.429000e+09,35.91
28,SFM,"Sprouts Farmers Market, Inc.",33.12,0.90,2.78,919940.0,1874000.0,3.673000e+09,15.77

In [4]:
si.get_day_losers()

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM)
0,FRGE,"Forge Global Holdings, Inc.",21.51,-4.69,-17.90,313805.0,798373.0,3.640000e+09,NaN
1,KIND,"Nextdoor Holdings, Inc.",5.37,-1.06,-16.49,2237000.0,1678000.0,2.073000e+09,NaN
2,NRGV,"Energy Vault Holdings, Inc.",18.48,-3.16,-14.60,917082.0,1071000.0,2.470000e+09,NaN
3,AUR,"Aurora Innovation, Inc.",5.57,-0.89,-13.70,3462000.0,2562000.0,6.266000e+09,NaN
4,DAVE,Dave Inc.,6.38,-0.91,-12.48,671534.0,1437000.0,2.373000e+09,NaN
...,...,...,...,...,...,...,...,...,...
95,ZG,"Zillow Group, Inc.",47.00,-3.49,-6.91,503652.0,1045000.0,1.196800e+10,NaN
96,NVEI,Nuvei Corporation,69.89,-5.53,-7.33,175304.0,408663.0,1.001200e+10,98.44
97,LYSCF,Lynas Rare Earths Limited,7.61,-0.55,-6.68,114426.0,126152.0,6.872000e+09,33.55
98,TWST,Twist Bioscience Corporation,47.76,-3.49,-6.82,378442.0,959777.0,2.680000e+09,NaN
99,UMICY,Umicore SA,10.29,-0.73,-6.62,79715.0,121608.0,9.976000e+09,14.56

In [5]:
si.get_day_most_active()

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM)
0,TWTR,"Twitter, Inc.",50.650,-0.330,-0.64,125422000.0,26383000.0,40556000000.0,NaN
1,TLRY,"Tilray Brands, Inc.",7.380,0.340,4.91,111013000.0,33083000.0,3545000000.0,NaN
2,AMD,"Advanced Micro Devices, Inc.",102.780,-4.040,-3.79,71903000.0,104981000.0,167254000000.0,39.99
3,F,Ford Motor Company,15.250,-0.570,-3.60,62632000.0,96056000.0,61287000000.0,3.43
4,AAPL,Apple Inc.,171.830,-3.230,-1.85,54540000.0,94254000.0,2.804T,28.57
...,...,...,...,...,...,...,...,...,...
95,LYG,Lloyds Banking Group plc,2.325,-0.045,-1.90,7739000.0,13480000.0,42259000000.0,5.93
96,ULCC,"Frontier Group Holdings, Inc.",11.100,-0.820,-6.88,7656000.0,1964000.0,2414000000.0,NaN
97,HBAN,Huntington Bancshares Incorporated,14.120,-0.250,-1.74,7550000.0,12891000.0,20401000000.0,15.69
98,SIRI,Sirius XM Holdings Inc.,6.570,-0.050,-0.68,7510000.0,21757000.0,25958000000.0,20.61
99,DIS,The Walt Disney Company,131.470,-4.150,-3.06,7466000.0,11869000.0,239358000000.0,78.12

## III. stats_valuation에서 per 가져오기

In [7]:
si.get_stats_valuation('MSFT')

,Unnamed: 0,As of Date: 4/5/2022Current,12/31/2021,9/30/2021,6/30/2021,3/31/2021
0,Market Cap (intraday),2.36T,2.52T,2.12T,2.04T,1.78T
1,Enterprise Value,2.30T,2.46T,2.05T,1.98T,1.71T
2,Trailing P/E,33.54,37.62,35.02,36.91,35.14
3,Forward P/E,29.15,36.90,31.55,32.57,29.24
4,PEG Ratio (5 yr expected),2.17,2.87,2.60,2.65,2.17
5,Price/Sales (ttm),12.90,14.48,12.76,12.91,11.76
6,Price/Book (mrq),14.76,16.60,14.91,15.14,13.64
7,Enterprise Value/Revenue,12.44,47.46,45.34,42.88,41.09
8,Enterprise Value/EBITDA,24.23,92.52,84.64,84.92,82.37