## 과제
- per 불러오기
- 모든 주식 per 테이블 만들기
- per 분포표만들기

## I. 페키지 셋팅

In [1]:
!pip install yahoo_fin
!pip install requests_html

Collecting yahoo_fin
  Downloading yahoo_fin-0.8.9.1-py3-none-any.whl (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (1.3.5)
Collecting requests-html
  Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)
Collecting feedparser
  Downloading feedparser-6.0.8-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 4.0 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (2.23.0)
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->yahoo_fin) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (1.24.3)
Collecting pyppeteer>=0.0.14
  Downloading pyppeteer-1.0.2-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.8 MB/s
Collecting w3lib
  Downloading w3lib-1.22.0-py2.py3-none-any.whl (20 kB)
Collecting pyquery
  Downloading pyquery-1.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests-html->yahoo_fin) (0.0.1)
Collecting parse
  Downloading parse-1.19.0.tar.gz (30 kB)
Collecting fake-useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Collecting websockets<11.0,>=10.0
  Downloading websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)
     |████████████████████████████████| 112 kB 42.5 MB/s
Collecting pyee<9.0.0,>=8.1.0
  Downloading pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.64.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.11.3)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 64.0 MB/s
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.8.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests-html->yahoo_fin) (4.6.3)
Collecting cssselect>0.7.9
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests-html->yahoo_fin) (4.2.6)
Building wheels for collected packages: fake-useragent, parse, sgmllib3k
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-py3-none-any.whl size=13502 sha256=7ae9a4bd1296468d58712ada63488c25ce04c1cc4e6a3aab0f2a907bb073fc7e
  Stored in directory: /root/.cache/pip/wheels/ed/f7/62/50ab6c9a0b5567267ab76a9daa9d06315704209b2c5d032031
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-py3-none-any.whl size=24591 sha256=0712c02e3b8050e10e1dbb5bbcf95cca6e05df059a84da04e77dda27f91bf1c0
  Stored in directory: /root/.cache/pip/wheels/9c/aa/cc/f2228050ccb40f22144b073f15a2c84f11204f29fc0dce028e
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6066 sha256=04fda83dd9c7d2855b7e4eedbcd599fcd27c9c7a5725d066a18c203b7ac5d940
  Stored in directory: /root/.cache/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built fake-useragent parse sgmllib3k
Installing collected packages: websockets, urllib3, pyee, cssselect, w3lib, sgmllib3k, pyquery, pyppeteer, parse, fake-useragent, requests-html, feedparser, yahoo-fin
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed cssselect-1.1.0 fake-useragent-0.1.11 feedparser-6.0.8 parse-1.19.0 pyee-8.2.2 pyppeteer-1.0.2 pyquery-1.4.3 requests-html-0.10.0 sgmllib3k-1.0.0 urllib3-1.25.11 w3lib-1.22.0 websockets-10.3 yahoo-fin-0.8.9.1
Requirement already satisfied: requests_html in /usr/local/lib/python3.7/dist-packages (0.10.0)
Requirement already satisfied: fake-useragent in /usr/local/lib/python3.7/dist-packages (from requests_html) (0.1.11)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from requests_html) (2.23.0)
Requirement already satisfied: pyquery in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.4.3)
Requirement already satisfied: w3lib in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.22.0)
Requirement already satisfied: parse in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.19.0)
Requirement already satisfied: pyppeteer>=0.0.14 in /usr/local/lib/python3.7/dist-packages (from requests_html) (1.0.2)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests_html) (0.0.1)
Requirement already satisfied: certifi>=2021 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (2021.10.8)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (1.4.4)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (4.64.0)
Requirement already satisfied: websockets<11.0,>=10.0 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (10.3)
Requirement already satisfied: urllib3<2.0.0,>=1.25.8 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (1.25.11)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (8.2.2)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests_html) (4.11.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests_html) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests_html) (4.1.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests_html) (4.6.3)
Requirement already satisfied: cssselect>0.7.9 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests_html) (1.1.0)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests_html) (4.2.6)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->requests_html) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->requests_html) (3.0.4)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from w3lib->requests_html) (1.15.0)

In [2]:
import yahoo_fin.stock_info as si
import pandas as pd

## II.기타 필요자료

### 매일 현재 상승 상위 100종목
### 하락 상위 100종목
### 거래량 100종목

In [3]:
si.get_day_gainers()

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM)
0,ICHBF,"Industrias CH, S. A. B. de C. V.",10.280,2.680,35.23,20000.0,0.0,5.010000e+09,35.69
1,EGRNF,China Evergrande Group,0.200,0.031,18.34,24300.0,118445.0,3.165000e+09,1.06
2,PHJMF,PT Hanjaya Mandala Sampoerna Tbk,0.066,0.007,11.86,93400.0,181834.0,8.160000e+09,NaN
3,WFG,West Fraser Timber Co. Ltd.,87.120,6.900,8.61,265761.0,318895.0,9.245000e+09,3.22
4,AVNT,Avient Corporation,51.370,3.490,7.29,100472.0,441896.0,4.696000e+09,20.47
5,RCI,Rogers Communications Inc.,62.270,3.790,6.48,204806.0,351347.0,3.158500e+10,25.47
6,DANOY,Danone S.A.,12.140,0.710,6.21,23362.0,819619.0,3.887600e+10,19.11
7,BKRKY,PT Bank Rakyat Indonesia (Persero) Tbk,16.770,0.880,5.54,38363.0,89283.0,5.085400e+10,18.63
8,OMC,Omnicom Group Inc.,85.440,4.620,5.72,736734.0,2027000.0,1.768200e+10,13.08
9,KUBTY,Kubota Corporation,90.450,4.470,5.20,17323.0,50111.0,2.175800e+10,15.80
10,CAR,"Avis Budget Group, Inc.",300.930,15.580,5.46,204438.0,1064000.0,1.498400e+10,15.48
11,LPX,Louisiana-Pacific Corporation,65.840,3.050,4.86,182281.0,1161000.0,5.664000e+09,4.67
12,IBM,International Business Machines Corporation,135.120,5.970,4.62,4215000.0,5050000.0,1.211060e+11,21.28
13,ONTO,Onto Innovation Inc.,75.080,3.130,4.35,24193.0,314422.0,3.712000e+09,26.25
14,MLI,"Mueller Industries, Inc.",58.740,2.420,4.30,28061.0,368791.0,3.362000e+09,7.12
15,BCC,Boise Cascade Company,79.050,3.240,4.28,74033.0,474763.0,3.118000e+09,4.40
16,VEOEY,Veolia Environnement S.A.,30.890,1.190,4.01,15903.0,76245.0,2.145500e+10,43.94
17,VRTV,Veritiv Corporation,151.010,5.790,3.99,22227.0,94170.0,2.270000e+09,16.76
18,CRH,CRH plc,41.260,1.580,3.97,146540.0,732985.0,3.161700e+10,12.66
19,ASML,ASML Holding N.V.,641.400,24.250,3.93,565790.0,1152000.0,2.582290e+11,41.36
20,ASAI,Sendas Distribuidora S.A.,18.180,0.630,3.59,121238.0,185318.0,4.897000e+09,14.37
21,EKTAY,Elekta AB (publ),7.560,0.280,3.79,23314.0,30808.0,2.905000e+09,24.55
22,BUD,Anheuser-Busch InBev SA/NV,61.380,2.190,3.70,335542.0,1632000.0,1.246580e+11,26.92
23,VC,Visteon Corporation,100.410,3.560,3.68,24779.0,378778.0,2.812000e+09,69.73
24,CXOXF,Core Lithium Ltd,1.150,0.040,3.60,15650.0,167688.0,2.005000e+09,NaN
25,TTD,"The Trade Desk, Inc.",69.260,2.370,3.54,2440000.0,6616000.0,3.366200e+10,247.36
26,EBR-B,Centrais Elétricas Brasileiras S.A. - Eletrobrás,8.880,0.300,3.44,16015.0,25061.0,1.461100e+10,11.67
27,ADNT,Adient plc,37.170,1.260,3.51,105059.0,1162000.0,3.522000e+09,3.93
28,EXPGY,Experian plc,36.540,1.210,3.42,29454.0,151947.0,3.369600e+10,34.12
29,THNPY,Technip Energies N.V.,13.310,0.430,3.38,20093.0,76763.0,2.350000e+09,9.05
30,MAN,ManpowerGroup Inc.,98.290,3.210,3.37,22909.0,472683.0,5.327000e+09,14.22
31,EVO,Evotec SE,14.130,0.450,3.29,23485.0,72486.0,5.047000e+09,17.52
32,ALV,"Autoliv, Inc.",78.240,2.450,3.23,222138.0,749954.0,6.849000e+09,15.77
33,LZ,"LegalZoom.com, Inc.",15.900,0.550,3.58,149881.0,1340000.0,3.155000e+09,NaN
34,STM,STMicroelectronics N.V.,38.840,1.160,3.08,903093.0,4270000.0,3.512600e+10,17.98
35,KLAC,KLA Corporation,348.410,10.590,3.13,182102.0,1529000.0,5.251100e+10,17.95
36,SSDOY,"Shiseido Company, Limited",48.160,1.470,3.15,206972.0,66413.0,1.929000e+10,57.47
37,VWDRY,Vestas Wind Systems A/S,10.010,0.300,3.09,61522.0,930832.0,3.021500e+10,167.93
38,TTM,Tata Motors Limited,29.020,0.830,2.94,59580.0,1126000.0,2.222600e+10,NaN
39,BTEGF,Baytex Energy Corp.,5.440,0.180,3.46,28216.0,682155.0,3.096000e+09,2.43
40,WDC,Western Digital Corporation,50.540,1.590,3.26,841513.0,3982000.0,1.581600e+10,7.96
41,VST,Vistra Corp.,25.570,0.750,3.02,530751.0,4594000.0,1.127600e+10,NaN
42,HTHIY,"Hitachi, Ltd.",95.320,2.780,3.00,35896.0,89177.0,4.609600e+10,9.06
43,JTKWY,Just Eat Takeaway.com N.V.,5.880,0.220,3.89,43807.0,1968000.0,6.416000e+09,NaN

In [4]:
si.get_day_losers()

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM)
0,NFLX,"Netflix, Inc.",227.51,-121.10,-34.74,30883000.0,8436000.0,1.010770e+11,20.24
1,RBLX,Roblox Corporation,36.60,-5.40,-12.85,7526000.0,24922000.0,2.163900e+10,NaN
2,BKR,Baker Hughes Company,32.99,-3.75,-10.21,4560000.0,11608000.0,3.578700e+10,NaN
3,SPOT,Spotify Technology S.A.,125.37,-12.04,-8.76,1099000.0,2402000.0,2.415400e+10,NaN
4,LGF-A,Lions Gate Entertainment Corp.,13.49,-1.35,-9.10,82349.0,550329.0,2.901000e+09,NaN
...,...,...,...,...,...,...,...,...,...
95,YY,JOYY Inc.,38.42,-1.49,-3.73,84017.0,918600.0,2.829000e+09,NaN
96,LLKKF,Lake Resources NL,1.67,-0.08,-4.57,272576.0,1270000.0,2.142000e+09,NaN
97,BILL,"Bill.com Holdings, Inc.",198.00,-8.82,-4.26,114143.0,2243000.0,2.051000e+10,NaN
98,GGR,Gogoro Inc.,8.59,-0.35,-3.95,56014.0,465113.0,2.054000e+09,NaN
99,BRZE,"Braze, Inc.",45.15,-1.85,-3.93,163085.0,678501.0,4.209000e+09,NaN

In [5]:
si.get_day_most_active()

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM)
0,NFLX,"Netflix, Inc.",227.510,-121.100,-34.74,30892000.0,8436000.0,101077000000.0,20.24
1,F,Ford Motor Company,16.190,0.040,0.25,11126000.0,85793000.0,65063999999.999992,3.64
2,AMD,"Advanced Micro Devices, Inc.",95.750,-1.180,-1.22,11062000.0,107086000.0,155820000000.0,37.26
3,DIDI,DiDi Global Inc.,1.968,-0.052,-2.57,10248000.0,51724000.0,9492000000.0,NaN
4,AAPL,Apple Inc.,166.760,-0.640,-0.38,9856000.0,92471000.0,2.721T,27.72
5,WBD,"Warner Bros. Discovery, Inc.",23.260,-1.230,-5.02,9633000.0,12698000.0,11249000000.0,16.88
6,DIS,The Walt Disney Company,125.750,-6.150,-4.66,9410000.0,11734000.0,228951000000.0,74.72
7,NIO,NIO Inc.,18.810,-1.070,-5.36,9329000.0,73892000.0,36194000000.0,NaN
8,TWTR,"Twitter, Inc.",45.560,-0.600,-1.30,8830000.0,42549000.0,34789000000.0,NaN
9,BAC,Bank of America Corporation,40.130,0.560,1.43,7998000.0,55171000.0,323572000000.0,11.24
10,AAL,American Airlines Group Inc.,19.590,0.000,0.01,7762000.0,44939000.0,12718000000.0,NaN
11,SOFI,"SoFi Technologies, Inc.",7.030,-0.380,-5.20,7917000.0,62308000.0,5617000000.0,NaN
12,NVDA,NVIDIA Corporation,218.670,-3.310,-1.49,7453000.0,54952000.0,544926000000.000061,56.80
13,RBLX,Roblox Corporation,36.600,-5.400,-12.85,7543000.0,24922000.0,21639000000.0,NaN
14,FB,"Meta Platforms, Inc.",207.120,-10.180,-4.69,6729000.0,37836000.0,562247000000.0,15.04
15,SNAP,Snap Inc.,31.410,-2.230,-6.62,6501000.0,36315000.0,51011000000.0,NaN
16,MU,"Micron Technology, Inc.",74.870,2.140,2.94,6304000.0,24102000.0,83605000000.0,9.42
17,NOK,Nokia Oyj,5.300,0.100,1.98,5888000.0,28413000.0,30161000000.0,17.05
18,PLTR,Palantir Technologies Inc.,12.810,-0.100,-0.77,5853000.0,51352000.0,26006000000.0,NaN
19,VALE,Vale S.A.,18.130,-0.620,-3.31,5993000.0,36521000.0,86068000000.0,3.49
20,TLRY,"Tilray Brands, Inc.",5.520,-0.310,-5.32,5540000.0,33786000.0,2747000000.0,NaN
21,PARA,Paramount Global,33.130,-3.150,-8.69,5159000.0,12941000.0,21581000000.0,4.78

## III. stats_valuation에서 per 가져오기

In [6]:
si.get_stats_valuation('MSFT')

,Unnamed: 0,As of Date: 4/18/2022Current,12/31/2021,9/30/2021,6/30/2021,3/31/2021
0,Market Cap (intraday),2.10T,2.52T,2.12T,2.04T,1.78T
1,Enterprise Value,2.04T,2.46T,2.05T,1.98T,1.71T
2,Trailing P/E,29.80,37.62,35.02,36.91,35.14
3,Forward P/E,25.77,36.90,31.55,32.57,29.24
4,PEG Ratio (5 yr expected),1.91,2.87,2.60,2.65,2.17
5,Price/Sales (ttm),11.46,14.48,12.76,12.91,11.76
6,Price/Book (mrq),13.11,16.60,14.91,15.14,13.64
7,Enterprise Value/Revenue,11.01,47.46,45.34,42.88,41.09
8,Enterprise Value/EBITDA,21.46,92.52,84.64,84.92,82.37

In [ ]:
a = si.get_analysts_info('MSFT')
print(a)

#IV.for문으로 여러 회사 확인하기

In [26]:
#Semiconductor SOXX ETF holdings (top 10)
soxx_etf_holdings = ['INTC','AVGO','TXN','NVDA','QCOM','AMAT','MU','LRCX','KLAC'] #'TSMC (ADR) fail to recall

In [27]:
soxx_etf_holdings

['INTC', 'AVGO', 'TXN', 'NVDA', 'QCOM', 'AMAT', 'MU', 'LRCX', 'KLAC']

In [30]:
for i in soxx_etf_holdings:
 print( i ,si.get_stats_valuation(i))

INTC                   Unnamed: 0 As of Date: 4/18/2022Current 12/31/2021  \
0      Market Cap (intraday)                      186.73B    209.60B
1           Enterprise Value                      196.42B    215.27B
2               Trailing P/E                         9.40      10.00
3                Forward P/E                        13.24      14.22
4  PEG Ratio (5 yr expected)                         2.65       2.85
5          Price/Sales (ttm)                         2.36       2.69
6           Price/Book (mrq)                         1.96       2.33
7   Enterprise Value/Revenue                         2.49      10.49
8    Enterprise Value/EBITDA                         5.76      25.62

  9/30/2021 6/30/2021 3/31/2021
0   216.69B   227.76B   258.43B
1   227.24B   241.25B   270.94B
2     11.84     12.62     12.96
3     12.02     12.67     14.06
4      2.06      2.53      2.81
5      2.83      3.02      3.48
6      2.54      2.85      3.19
7     11.84     12.29     13.77
8     22.81     27.63     38.72
AVGO                   Unnamed: 0 As of Date: 4/18/2022Current 1/31/2022  \
0      Market Cap (intraday)                      234.29B   240.21B
1           Enterprise Value                      263.60B   267.80B
2               Trailing P/E                        32.72     39.06
3                Forward P/E                        16.31     17.79
4  PEG Ratio (5 yr expected)                         1.15      1.11
5          Price/Sales (ttm)                         8.64      9.16
6           Price/Book (mrq)                        10.20      9.62
7   Enterprise Value/Revenue                         9.25     34.75
8    Enterprise Value/EBITDA                        16.91     61.13

  10/31/2021 7/31/2021 4/30/2021 1/31/2021
0    218.84B   199.14B   186.27B   183.22B
1    248.22B   230.09B   218.67B   216.70B
2      39.38     45.11     52.74     71.17
3      17.39     16.26     16.95     17.27
4       1.21      1.14      1.25      1.13
5       8.58      8.09      7.82      7.94
6       9.02      8.32      7.77      7.70
7      33.51     33.95     33.08     32.56
8      60.48     63.14     63.27     62.14
TXN                   Unnamed: 0 As of Date: 4/18/2022Current 12/31/2021  \
0      Market Cap (intraday)                      160.27B    174.15B
1           Enterprise Value                      158.65B    172.10B
2               Trailing P/E                        21.02      24.19
3                Forward P/E                        18.90      22.47
4  PEG Ratio (5 yr expected)                         2.28       2.11
5          Price/Sales (ttm)                         8.86      10.02
6           Price/Book (mrq)                        12.02      14.33
7   Enterprise Value/Revenue                         8.65      35.62
8    Enterprise Value/EBITDA                        15.78      63.16

  9/30/2021 6/30/2021 3/31/2021
0   177.49B   177.51B   174.48B
1   176.35B   177.07B   174.96B
2     26.81     29.14     31.66
3     23.31     26.95     28.82
4      2.13      2.49      2.87
5     10.70     11.61     12.19
6     15.91     17.46     18.99
7     37.98     38.66     40.79
8     68.54     69.91     78.60
NVDA                   Unnamed: 0 As of Date: 4/18/2022Current 1/31/2022  \
0      Market Cap (intraday)                      619.19B   613.62B
1           Enterprise Value                      609.67B   606.15B
2               Trailing P/E                        55.22     75.46
3                Forward P/E                        38.02     47.62
4  PEG Ratio (5 yr expected)                         2.80      2.61
5          Price/Sales (ttm)                        20.02     25.55
6           Price/Book (mrq)                        23.27     25.78
7   Enterprise Value/Revenue                        22.65     79.31
8    Enterprise Value/EBITDA                        53.71    187.37

  10/31/2021 7/31/2021 4/30/2021 1/31/2021
0    639.17B   485.92B   373.67B   321.63B
1    632.31B   480.99B   369.82B   319.17B
2      91.47     92.19     87.01     84.90
3      54.95     50.00     43.48     46.08
4       3.84      3.50      3.73      2.88
5      29.52     25.54     22.61     21.97
6      30.25     25.88     22.12     21.01
7      89.02     73.92     65.33     63.80
8     210.91    175.54    155.52    176.24
QCOM                   Unnamed: 0 As of Date: 4/18/2022Current 12/31/2021  \
0      Market Cap (intraday)                      154.30B    205.73B
1           Enterprise Value                      158.74B    209.06B
2               Trailing P/E                        15.68      23.24
3                Forward P/E                        11.76      17.30
4  PEG Ratio (5 yr expected)                         0.75       1.07
5          Price/Sales (ttm)                         4.35       6.26
6           Price/Book (mrq)                        13.61      20.68
7   Enterprise Value/Revenue                         4.40      19.53
8    Enterprise Value/EBITDA                        11.57      47.41

  9/30/2021 6/30/2021 3/31/2021
0   145.10B   161.23B   149.69B
1   147.94B   165.43B   153.13B
2     16.12     20.51     22.70
3     14.12     16.45     18.05
4      0.64      0.66      0.76
5      4.55      5.58      5.70
6     17.75     21.72     20.28
7     15.85     20.53     19.30
8     38.44     59.06     57.63
AMAT                   Unnamed: 0 As of Date: 4/18/2022Current 1/31/2022  \
0      Market Cap (intraday)                      100.14B   122.07B
1           Enterprise Value                      100.16B   122.36B
2               Trailing P/E                        15.79     21.59
3                Forward P/E                        13.97     16.92
4  PEG Ratio (5 yr expected)                         1.70      1.95
5          Price/Sales (ttm)                         4.28      5.51
6           Price/Book (mrq)                         8.42      9.97
7   Enterprise Value/Revenue                         4.14     19.51
8    Enterprise Value/EBITDA                        12.38     58.71

  10/31/2021 7/31/2021 4/30/2021 1/31/2021
0    123.39B   127.89B   121.78B    88.72B
1    122.59B   126.83B   120.86B    88.69B
2      23.77     29.15     31.75     24.66
3      17.42     18.83     22.22     19.65
4       1.08      1.22      1.77      2.20
5       5.83      6.52      6.73      5.19
6      10.11     10.66     10.61      8.39
7      20.02     20.47     21.65     17.18
8      56.55     59.41     70.97     63.58
MU                   Unnamed: 0 As of Date: 4/18/2022Current 2/28/2022  \
0      Market Cap (intraday)                       78.31B    99.50B
1           Enterprise Value                       75.80B    97.47B
2               Trailing P/E                         8.82     13.73
3                Forward P/E                         7.52      9.66
4  PEG Ratio (5 yr expected)                         0.89      1.04
5          Price/Sales (ttm)                         2.56      3.42
6           Price/Book (mrq)                         1.64      2.17
7   Enterprise Value/Revenue                         2.43     12.52
8    Enterprise Value/EBITDA                         4.58     22.64

  11/30/2021 8/31/2021 5/31/2021 2/28/2021
0     94.09B    82.97B    94.36B   102.39B
1     92.74B    81.85B    94.32B   102.52B
2      16.34     20.36     29.94     34.54
3       9.13      6.88      8.26     21.83
4       1.02      0.27      0.38      1.02
5       3.46      3.29      4.06      4.70
6       2.14      1.96      2.32      2.57
7      12.06      9.89     12.71     16.44
8      21.89     17.78     27.67     46.05
LRCX                   Unnamed: 0 As of Date: 4/18/2022Current 12/31/2021  \
0      Market Cap (intraday)                       63.63B    100.88B
1           Enterprise Value                       63.30B    101.26B
2               Trailing P/E                        14.23      24.31
3                Forward P/E                        11.72      20.45
4  PEG Ratio (5 yr expected)                         0.86       1.51
5          Price/Sales (ttm)                         3.95       6.58
6           Price/Book (mrq)                         9.83      17.33
7   Enterprise Value/Revenue                         3.83      23.96
8    Enterprise Value/EBITDA                        11.14      68.21

  9/30/2021 6/30/2021 3/31/2021
0    80.14B    92.73B    84.89B
1    79.41B    92.75B    84.67B
2     21.16     27.51     29.57
3     16.72     20.33     21.28
4      1.42      0.95      1.24
5      5.65      7.17      7.34
6     13.30     17.25     15.41
7     18.45     22.38     22.01
8     54.08     64.46     65.55
KLAC                   Unnamed: 0 As of Date: 4/18/2022Current 12/31/2021  \
0      Market Cap (intraday)                       48.45B     64.88B
1           Enterprise Value                       49.18B     65.80B
2               Trailing P/E                        16.55      24.38
3                Forward P/E                        13.76      20.58
4  PEG Ratio (5 yr expected)                         1.29       1.85
5          Price/Sales (ttm)                         6.06       8.91
6           Price/Book (mrq)                        11.97      16.80
7   Enterprise Value/Revenue                         6.02      27.97
8    Enterprise Value/EBITDA                        13.90      62.65

  9/30/2021 6/30/2021 3/31/2021
0    50.76B    49.53B    50.67B
1    51.81B    50.63B    51.94B
2     25.02     27.24     37.72
3     17.99     19.49     22.37
4      1.83      1.56      2.10
5      7.52      7.83      8.51
6     15.03     15.90     17.26
7     24.86     26.30     28.80
8     58.25     60.75     68.00

In [29]:
print (si.get_stats_valuation('MSFT'))

                  Unnamed: 0 As of Date: 4/18/2022Current 12/31/2021  \
0      Market Cap (intraday)                        2.10T      2.52T
1           Enterprise Value                        2.04T      2.46T
2               Trailing P/E                        29.80      37.62
3                Forward P/E                        25.77      36.90
4  PEG Ratio (5 yr expected)                         1.91       2.87
5          Price/Sales (ttm)                        11.46      14.48
6           Price/Book (mrq)                        13.11      16.60
7   Enterprise Value/Revenue                        11.01      47.46
8    Enterprise Value/EBITDA                        21.46      92.52

  9/30/2021 6/30/2021 3/31/2021
0     2.12T     2.04T     1.78T
1     2.05T     1.98T     1.71T
2     35.02     36.91     35.14
3     31.55     32.57     29.24
4      2.60      2.65      2.17
5     12.76     12.91     11.76
6     14.91     15.14     13.64
7     45.34     42.88     41.09
8     84.64     84.92     82.37

In [25]:
si.get_stats_valuation('TSMC')

IndexError: ignored